"""Resource types are listed below for list-resource-aws.py.
"""

from dataclasses import dataclass
from typing import Any, Callable

@dataclass
class ResourceConfig:
    describe_method: str               # ec2 client method to call
    response_key: str                  # top-level key in the API response
    owner_key: str                     # ownership filter param ("OwnerIds" vs "Owners")
    id_field: str                      # API field name for the resource ID
    id_column: str                     # CSV column name for the ID (forced to "arn")
    meta_columns: list[str]            # non-tag metadata columns before rbrk_* tags
    extract_meta: Callable[[Any], list]
    trailing_columns: list[str]        # columns written after rbrk_* tags (e.g. description)
    extract_trailing: Callable[[Any], list]
    arn_formatter: Callable[[str, str, str], str]  # (id, region, account_id) -> ARN
    result_filter: Callable[[list, str], list] | None = None  # post-fetch filter when API lacks an owner param
    client_name: str = "ec2"          
    is_global: bool = False
    extra_kwargs: dict | None = None
    account_id_param: str = ""          # if set, pass {account_id_param: account_id} to the describe call
    # for s3-storage-lens and asg
    native_s3_tags: bool = False        # fetch tags per-bucket from its HOME region (S3), not RGT us-east-1
    tags_in_response: bool = False      # describe call already returns tags inline (e.g. ASG) -> skip RGT



RESOURCE_TYPES: dict[str, ResourceConfig] = {
    "acm-certificate":  ResourceConfig(
        client_name="acm",
        describe_method="list_certificates",
        response_key="CertificateSummaryList",
        owner_key="",
        id_field="CertificateArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["domain_name", "status"],
        extract_meta=lambda x: [x.get("DomainName", ""), x.get("Status", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "alarm": ResourceConfig(
        client_name="cloudwatch",
        describe_method="describe_alarms",
        response_key="MetricAlarms",
        owner_key="",
        id_field="AlarmArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["alarm_name", "state_value", "metric_name"],
        extract_meta=lambda x: [x.get("AlarmName", ""), x.get("StateValue", ""), x.get("MetricName", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "ami":            ResourceConfig(
        describe_method="describe_images",
        response_key="Images",
        owner_key="Owners",
        id_field="ImageId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:image/{id}",
        meta_columns=["creation_date", "state", "architecture"],
        extract_meta=lambda i: [i.get("CreationDate", ""), i.get("State", ""), i.get("Architecture", "")],
        trailing_columns=["description"],
        extract_trailing=lambda i: [i.get("Description", "")],
    ),
    "app-elb":                ResourceConfig(
        client_name="elbv2",
        describe_method="describe_load_balancers",
        response_key="LoadBalancers",
        owner_key="",
        id_field="LoadBalancerArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["dns_name", "type", "state"],
        extract_meta=lambda x: [x.get("DNSName", ""), x.get("Type", ""), x.get("State", {}).get("Code", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "app-elb-target-group":                             ResourceConfig(
        client_name="elbv2",
        describe_method="describe_target_groups",
        response_key="TargetGroups",
        owner_key="",
        id_field="TargetGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["target_group_name", "protocol", "port"],
        extract_meta=lambda x: [x.get("TargetGroupName", ""), x.get("Protocol", ""), str(x.get("Port", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "appstream-fleet":                        ResourceConfig(
        client_name="appstream",
        describe_method="describe_fleets",
        response_key="Fleets",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "state", "instance_type"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("State", ""), x.get("InstanceType", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "appstream-stack":                        ResourceConfig(
        client_name="appstream",
        describe_method="describe_stacks",
        response_key="Stacks",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "asg":            ResourceConfig(
        client_name="autoscaling",
        describe_method="describe_auto_scaling_groups",
        response_key="AutoScalingGroups",
        owner_key="",
        id_field="AutoScalingGroupARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["auto_scaling_group_name"],
        extract_meta=lambda x: [x.get("AutoScalingGroupName", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # describe_auto_scaling_groups returns each group's Tags inline; RGT can't
        # tag ASGs, so read tags from the describe response instead.
        tags_in_response=True,
    ),
    "athena-work-group":                          ResourceConfig(
        client_name="athena",
        describe_method="list_work_groups",
        response_key="WorkGroups",
        owner_key="",
        id_field="Name",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:athena:{r}:{a}:workgroup/{id}",
        meta_columns=["state", "description"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Description", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "cfn":            ResourceConfig(
        client_name="cloudformation",
        describe_method="describe_stacks",
        response_key="Stacks",
        owner_key="",
        id_field="StackId",              # StackId is already a full ARN
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["stack_name", "stack_status", "creation_time"],
        extract_meta=lambda x: [x.get("StackName", ""), x.get("StackStatus", ""), str(x.get("CreationTime", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "cloudhsm-backup":                        ResourceConfig(
        client_name="cloudhsmv2",
        describe_method="describe_backups",
        response_key="Backups",
        owner_key="",
        id_field="BackupId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:cloudhsm:{r}:{a}:backup/{id}",
        meta_columns=["backup_state", "cluster_id"],
        extract_meta=lambda x: [x.get("BackupState", ""), x.get("ClusterId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "cloudhsm-cluster":                         ResourceConfig(
        client_name="cloudhsmv2",
        describe_method="describe_clusters",
        response_key="Clusters",
        owner_key="",
        id_field="ClusterId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:cloudhsm:{r}:{a}:cluster/{id}",
        meta_columns=["state"],
        extract_meta=lambda x: [x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "comprehend-sentiment-detection-job":                                           ResourceConfig(
        client_name="comprehend",
        describe_method="list_sentiment_detection_jobs",
        response_key="SentimentDetectionJobPropertiesList",
        owner_key="",
        id_field="JobArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["job_name", "job_status"],
        extract_meta=lambda x: [x.get("JobName", ""), x.get("JobStatus", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "comprehend-topics-detection-job":                                        ResourceConfig(
        client_name="comprehend",
        describe_method="list_topics_detection_jobs",
        response_key="TopicsDetectionJobPropertiesList",
        owner_key="",
        id_field="JobArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["job_name", "job_status"],
        extract_meta=lambda x: [x.get("JobName", ""), x.get("JobStatus", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "customer-gateway":                         ResourceConfig(
        describe_method="describe_customer_gateways",
        response_key="CustomerGateways",
        owner_key="",
        id_field="CustomerGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:customer-gateway/{id}",
        meta_columns=["state", "type", "bgp_asn"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Type", ""), str(x.get("BgpAsn", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "distribution":                     ResourceConfig(
        client_name="cloudfront", describe_method="list_distributions",
        response_key="DistributionList", owner_key="",
        id_field="ARN", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["domain_name", "status", "enabled"],
        extract_meta=lambda x: [x.get("DomainName", ""), x.get("Status", ""), str(x.get("Enabled", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        result_filter=lambda res, acc: res.get("Items", []) if isinstance(res, dict) else [],
        is_global=True,
    ),
    "dynamodb-table":                       ResourceConfig(
        client_name="dynamodb",
        describe_method="list_tables",
        response_key="TableNames",
        owner_key="",
        id_field="TableName",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:dynamodb:{r}:{a}:table/{name}",
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda names, acc: [{"TableName": n} for n in (names or [])],
    ),
    "ebs":            ResourceConfig(
        describe_method="describe_volumes",
        response_key="Volumes",
        owner_key="",
        id_field="VolumeId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:volume/{id}",
        meta_columns=["create_time", "size_gb", "state", "volume_type", "availability_zone"],
        extract_meta=lambda v: [
            v.get("CreateTime", ""), str(v.get("Size", "")), v.get("State", ""),
            v.get("VolumeType", ""), v.get("AvailabilityZone", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "ebs-snapshot":                     ResourceConfig(
        describe_method="describe_snapshots",
        response_key="Snapshots",
        owner_key="OwnerIds",
        id_field="SnapshotId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:snapshot/{id}",
        meta_columns=["completion_time"],
        extract_meta=lambda s: [s.get("CompletionTime", "")],
        trailing_columns=["description"],
        extract_trailing=lambda s: [s.get("Description", "")],
    ),
    "ec2":            ResourceConfig(
        client_name="ec2",
        describe_method="describe_instances",
        response_key="Reservations",
        owner_key="",
        id_field="InstanceId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:instance/{id}",
        meta_columns=["instance_type", "state", "vpc_id"],
        extract_meta=lambda i: [
            i.get("InstanceType", ""),
            i.get("State", {}).get("Name", ""),
            i.get("VpcId", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda res, acc: [i for r in res for i in r.get("Instances", [])],
    ),
    "ecr":            ResourceConfig(
        client_name="ecr",
        describe_method="describe_repositories",
        response_key="repositories",       # NOTE: unlike most services, key is lowercase
        owner_key="",
        id_field="repositoryArn",         # NOTE: ecr uses lowercase field names
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["repository_name", "repository_uri"],
        extract_meta=lambda x: [x.get("repositoryName", ""), x.get("repositoryUri", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "efs":            ResourceConfig(
        client_name="efs",
        describe_method="describe_file_systems",
        response_key="FileSystems",
        owner_key="",
        id_field="FileSystemId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:elasticfilesystem:{r}:{a}:file-system/{id}",
        meta_columns=["life_cycle_state", "creation_time"],
        extract_meta=lambda x: [x.get("LifeCycleState", ""), str(x.get("CreationTime", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "eks":            ResourceConfig(
        client_name="eks",
        describe_method="list_clusters",
        response_key="clusters",
        owner_key="",
        id_field="name",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:eks:{r}:{a}:cluster/{name}",
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda names, acc: [{"name": n} for n in (names or [])],
    ),
    "elastic-ip":                   ResourceConfig(
        describe_method="describe_addresses",
        response_key="Addresses",
        owner_key="",
        id_field="AllocationId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:elastic-ip/{id}",
        meta_columns=["public_ip", "domain", "instance_id"],
        extract_meta=lambda x: [x.get("PublicIp", ""), x.get("Domain", ""), x.get("InstanceId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "elb":            ResourceConfig(
        client_name="elb",
        describe_method="describe_load_balancers",
        response_key="LoadBalancerDescriptions",
        owner_key="",
        id_field="LoadBalancerName",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:elasticloadbalancing:{r}:{a}:loadbalancer/{id}",
        meta_columns=["dns_name", "scheme", "vpc_id"],
        extract_meta=lambda x: [x.get("DNSName", ""), x.get("Scheme", ""), x.get("VPCId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "event-bus":                  ResourceConfig(
        client_name="events",
        describe_method="list_event_buses",
        response_key="EventBuses",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "event-rule":                   ResourceConfig(
        client_name="events",
        describe_method="list_rules",
        response_key="Rules",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "state"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("State", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "firehose":                 ResourceConfig(
        client_name="firehose",
        describe_method="list_delivery_streams",
        response_key="DeliveryStreamNames",
        owner_key="",
        id_field="DeliveryStreamName",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:firehose:{r}:{a}:deliverystream/{name}",
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda names, acc: [{"DeliveryStreamName": n} for n in (names or [])],
    ),
    "flow-log":                 ResourceConfig(
        describe_method="describe_flow_logs",
        response_key="FlowLogs",
        owner_key="",
        id_field="FlowLogId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc-flow-log/{id}",
        meta_columns=["flow_log_status", "resource_id", "log_destination_type"],
        extract_meta=lambda x: [x.get("FlowLogStatus", ""), x.get("ResourceId", ""), x.get("LogDestinationType", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "globalaccelerator":                          ResourceConfig(
        client_name="globalaccelerator",
        describe_method="list_accelerators",
        response_key="Accelerators",
        owner_key="",
        id_field="AcceleratorArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "status"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("Status", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        is_global=True,
    ),
    "hostedzone":                   ResourceConfig(
        client_name="route53", describe_method="list_hosted_zones",
        response_key="HostedZones", owner_key="",
        id_field="Id", id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:route53:::hostedzone/{id.split('/')[-1]}",
        meta_columns=["zone_name", "record_count", "private"],
        extract_meta=lambda x: [x.get("Name", ""), str(x.get("ResourceRecordSetCount", "")), str(x.get("Config", {}).get("PrivateZone", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        is_global=True,
    ),
    "iam-policy":                   ResourceConfig(
        client_name="iam", describe_method="list_policies", response_key="Policies",
        owner_key="", id_field="Arn", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["policy_name", "attachment_count", "create_date"],
        extract_meta=lambda x: [x.get("PolicyName", ""), str(x.get("AttachmentCount", "")), str(x.get("CreateDate", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        extra_kwargs={"Scope": "Local"},   # needs the extra_kwargs engine tweak
        is_global=True,
    ),
    "iam-role":                 ResourceConfig(
        client_name="iam", describe_method="list_roles", response_key="Roles",
        owner_key="", id_field="Arn", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["role_name", "create_date", "path"],
        extract_meta=lambda x: [x.get("RoleName", ""), str(x.get("CreateDate", "")), x.get("Path", "")],
        trailing_columns=["description"], extract_trailing=lambda x: [x.get("Description", "")],
        is_global=True,
        # TAG WARNING: RGT GetResources does NOT support IAM roles -> empty tags.
        # Needs native iam.list_role_tags(RoleName=...).
    ),
    "iam-user":                 ResourceConfig(
        client_name="iam", describe_method="list_users", response_key="Users",
        owner_key="", id_field="Arn", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["user_name", "create_date", "path"],
        extract_meta=lambda x: [x.get("UserName", ""), str(x.get("CreateDate", "")), x.get("Path", "")],
        trailing_columns=[], extract_trailing=lambda _: [],
        is_global=True,
        # TAG WARNING: RGT GetResources does NOT support IAM users -> empty tags.
        # Needs native iam.list_user_tags(UserName=...).
    ),
    "internet-gateway":                         ResourceConfig(
        describe_method="describe_internet_gateways",
        response_key="InternetGateways",
        owner_key="",
        id_field="InternetGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:internet-gateway/{id}",
        meta_columns=["attached_vpc"],
        extract_meta=lambda x: [(x.get("Attachments") or [{}])[0].get("VpcId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "key-pair":                 ResourceConfig(
        describe_method="describe_key_pairs",
        response_key="KeyPairs",
        owner_key="",
        id_field="KeyPairId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:key-pair/{id}",
        meta_columns=["key_name", "key_type", "key_fingerprint"],
        extract_meta=lambda x: [x.get("KeyName", ""), x.get("KeyType", ""), x.get("KeyFingerprint", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "kms-key":                ResourceConfig(
        client_name="kms",
        describe_method="list_keys",
        response_key="Keys",
        owner_key="",
        id_field="KeyArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "lambda":               ResourceConfig(
        client_name="lambda",
        describe_method="list_functions",
        response_key="Functions",
        owner_key="",
        id_field="FunctionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["function_name", "runtime", "state"],
        extract_meta=lambda l: [l.get("FunctionName", ""), l.get("Runtime", ""), l.get("State", "")],
        trailing_columns=["description"],
        extract_trailing=lambda l: [l.get("Description", "")],
    ),
    "log-group":                  ResourceConfig(
        client_name="logs",
        describe_method="describe_log_groups",
        response_key="logGroups",
        owner_key="",
        id_field="arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn[:-2] if arn.endswith(":*") else arn,
        meta_columns=["log_group_name", "retention_in_days", "creation_time"],
        extract_meta=lambda x: [x.get("logGroupName", ""), str(x.get("retentionInDays", "")), str(x.get("creationTime", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "nat-gateway":                    ResourceConfig(
        describe_method="describe_nat_gateways",
        response_key="NatGateways",
        owner_key="",
        id_field="NatGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:natgateway/{id}",
        meta_columns=["vpc_id", "subnet_id", "state"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("SubnetId", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "network-acl":                    ResourceConfig(
        describe_method="describe_network_acls",
        response_key="NetworkAcls",
        owner_key="",
        id_field="NetworkAclId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:network-acl/{id}",
        meta_columns=["vpc_id", "is_default"],
        extract_meta=lambda x: [x.get("VpcId", ""), str(x.get("IsDefault", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "peering-connection":                           ResourceConfig(
        describe_method="describe_vpc_peering_connections",
        response_key="VpcPeeringConnections",
        owner_key="",
        id_field="VpcPeeringConnectionId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc-peering-connection/{id}",
        meta_columns=["status", "requester_vpc", "accepter_vpc"],
        extract_meta=lambda x: [
            x.get("Status", {}).get("Code", ""),
            x.get("RequesterVpcInfo", {}).get("VpcId", ""),
            x.get("AccepterVpcInfo", {}).get("VpcId", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "prefix-list":                    ResourceConfig(
        describe_method="describe_managed_prefix_lists",
        response_key="PrefixLists",
        owner_key="",
        id_field="PrefixListId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:prefix-list/{id}",
        meta_columns=["prefix_list_name", "state", "address_family"],
        extract_meta=lambda x: [x.get("PrefixListName", ""), x.get("State", ""), x.get("AddressFamily", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds":            ResourceConfig(
        client_name="rds",
        describe_method="describe_db_instances",
        response_key="DBInstances",
        owner_key="",
        id_field="DBInstanceArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["db_instance_class", "engine", "status"],
        extract_meta=lambda x: [x.get("DBInstanceClass", ""), x.get("Engine", ""), x.get("DBInstanceStatus", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster":                    ResourceConfig(
        client_name="rds",
        describe_method="describe_db_clusters",
        response_key="DBClusters",
        owner_key="",
        id_field="DBClusterArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["engine", "status", "engine_mode"],
        extract_meta=lambda x: [x.get("Engine", ""), x.get("Status", ""), x.get("EngineMode", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster-param-group":                                ResourceConfig(
        client_name="rds",
        describe_method="describe_db_cluster_parameter_groups",
        response_key="DBClusterParameterGroups",
        owner_key="",
        id_field="DBClusterParameterGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["db_parameter_group_family"],
        extract_meta=lambda x: [x.get("DBParameterGroupFamily", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster-snapshot":                             ResourceConfig(
        client_name="rds",
        describe_method="describe_db_cluster_snapshots",
        response_key="DBClusterSnapshots",
        owner_key="",
        id_field="DBClusterSnapshotArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["snapshot_type", "status", "engine"],
        extract_meta=lambda x: [x.get("SnapshotType", ""), x.get("Status", ""), x.get("Engine", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-param-group":                        ResourceConfig(
        client_name="rds",
        describe_method="describe_db_parameter_groups",
        response_key="DBParameterGroups",
        owner_key="",
        id_field="DBParameterGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["db_parameter_group_family"],
        extract_meta=lambda x: [x.get("DBParameterGroupFamily", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-snapshot":                     ResourceConfig(
        client_name="rds",
        describe_method="describe_db_snapshots",
        response_key="DBSnapshots",
        owner_key="",
        id_field="DBSnapshotArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["snapshot_type", "status", "engine"],
        extract_meta=lambda x: [x.get("SnapshotType", ""), x.get("Status", ""), x.get("Engine", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-subnet-group":                         ResourceConfig(
        client_name="rds",
        describe_method="describe_db_subnet_groups",
        response_key="DBSubnetGroups",
        owner_key="",
        id_field="DBSubnetGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["vpc_id", "status"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("SubnetGroupStatus", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-subscription":                         ResourceConfig(
        client_name="rds",
        describe_method="describe_event_subscriptions",
        response_key="EventSubscriptionsList",
        owner_key="",
        id_field="EventSubscriptionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["source_type", "status", "sns_topic_arn"],
        extract_meta=lambda x: [x.get("SourceType", ""), x.get("Status", ""), x.get("SnsTopicArn", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "resource-share-self":                            ResourceConfig(
        client_name="ram",
        describe_method="get_resource_shares",
        response_key="resourceShares",
        owner_key="",
        id_field="resourceShareArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "status"],
        extract_meta=lambda x: [x.get("name", ""), x.get("status", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        extra_kwargs={"resourceOwner": "SELF"},
    ),
    "route-table":                    ResourceConfig(
        describe_method="describe_route_tables",
        response_key="RouteTables",
        owner_key="",
        id_field="RouteTableId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:route-table/{id}",
        meta_columns=["vpc_id"],
        extract_meta=lambda x: [x.get("VpcId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "s3":           ResourceConfig(
        client_name="s3", describe_method="list_buckets", response_key="Buckets",
        owner_key="", id_field="Name", id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:s3:::{id}",
        meta_columns=["creation_date"],
        extract_meta=lambda x: [str(x.get("CreationDate", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        is_global=True,
        # RGT returns S3 tags only from the bucket's HOME region, so tags are
        # fetched natively per bucket (get_bucket_location + get_bucket_tagging)
        # instead of RGT us-east-1 -- otherwise non-us-east-1 buckets show empty.
        native_s3_tags=True,
    ),
    "s3-storage-lens":                        ResourceConfig(
        client_name="s3control",
        describe_method="list_storage_lens_configurations",
        response_key="StorageLensConfigurationList",
        owner_key="",
        id_field="StorageLensArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["id", "is_enabled"],
        extract_meta=lambda x: [x.get("Id", ""), str(x.get("IsEnabled", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        account_id_param="AccountId",   # s3control.list_storage_lens_configurations requires AccountId
    ),
    "secrets-manager":                        ResourceConfig(
        client_name="secretsmanager",
        describe_method="list_secrets",
        response_key="SecretList",
        owner_key="",
        id_field="ARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "last_changed_date"],
        extract_meta=lambda x: [x.get("Name", ""), str(x.get("LastChangedDate", ""))],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "security-group":                       ResourceConfig(
        describe_method="describe_security_groups",
        response_key="SecurityGroups",
        owner_key="",
        id_field="GroupId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:security-group/{id}",
        meta_columns=["group_name", "vpc_id"],
        extract_meta=lambda x: [x.get("GroupName", ""), x.get("VpcId", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "ses-email-identity":                           ResourceConfig(
        client_name="sesv2",
        describe_method="list_email_identities",
        response_key="EmailIdentities",
        owner_key="",
        id_field="IdentityName",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:ses:{r}:{a}:identity/{name}",
        meta_columns=["identity_type", "verified_for_sending_status"],
        extract_meta=lambda x: [x.get("IdentityType", ""), str(x.get("VerifiedForSendingStatus", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "snapshot":                 ResourceConfig(
        describe_method="describe_snapshots",
        response_key="Snapshots",
        owner_key="OwnerIds",
        id_field="SnapshotId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:snapshot/{id}",
        meta_columns=["completion_time"],
        extract_meta=lambda s: [s.get("CompletionTime", "")],
        trailing_columns=["description"],
        extract_trailing=lambda s: [s.get("Description", "")],
    ),
    "sns":            ResourceConfig(
        client_name="sns",
        describe_method="list_topics",
        response_key="Topics",
        owner_key="",
        id_field="TopicArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "sqs":            ResourceConfig(
        client_name="sqs",
        describe_method="list_queues",
        response_key="QueueUrls",
        owner_key="",
        id_field="QueueUrl",
        id_column="arn",
        arn_formatter=lambda url, r, a: f"arn:aws:sqs:{r}:{a}:{url.rstrip('/').split('/')[-1]}",
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda urls, acc: [{"QueueUrl": u} for u in (urls or [])],
    ),
    "ssm-document":                     ResourceConfig(
        client_name="ssm",
        describe_method="list_documents",
        response_key="DocumentIdentifiers",
        owner_key="",
        id_field="Name",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ssm:{r}:{a}:document/{id}",
        meta_columns=["document_type", "document_version"],
        extract_meta=lambda x: [x.get("DocumentType", ""), x.get("DocumentVersion", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # Restrict to self-owned documents; otherwise AWS's public documents flood the listing.
        extra_kwargs={"Filters": [{"Key": "Owner", "Values": ["Self"]}]},
    ),
    "ssm-parameter":                      ResourceConfig(
        client_name="ssm",
        describe_method="describe_parameters",
        response_key="Parameters",
        owner_key="",
        id_field="Name",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ssm:{r}:{a}:parameter/{id.lstrip('/')}",
        meta_columns=["type", "data_type"],
        extract_meta=lambda x: [x.get("Type", ""), x.get("DataType", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "subnet":               ResourceConfig(
        describe_method="describe_subnets",
        response_key="Subnets",
        owner_key="",
        id_field="SubnetId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:subnet/{id}",
        meta_columns=["vpc_id", "cidr_block", "availability_zone", "state"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("CidrBlock", ""), x.get("AvailabilityZone", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "transit-attachment":                           ResourceConfig(
        describe_method="describe_transit_gateway_attachments",
        response_key="TransitGatewayAttachments",
        owner_key="",
        id_field="TransitGatewayAttachmentId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:transit-gateway-attachment/{id}",
        meta_columns=["transit_gateway_id", "resource_type", "state"],
        extract_meta=lambda x: [x.get("TransitGatewayId", ""), x.get("ResourceType", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpc":            ResourceConfig(
        describe_method="describe_vpcs",
        response_key="Vpcs",
        owner_key="",
        id_field="VpcId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc/{id}",
        meta_columns=["state", "cidr_block", "is_default"],
        extract_meta=lambda x: [x.get("State", ""), x.get("CidrBlock", ""), str(x.get("IsDefault", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpc-endpoint":                     ResourceConfig(
        describe_method="describe_vpc_endpoints",
        response_key="VpcEndpoints",
        owner_key="",
        id_field="VpcEndpointId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc-endpoint/{id}",
        meta_columns=["vpc_id", "service_name", "state"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("ServiceName", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpn-connection":                       ResourceConfig(
        describe_method="describe_vpn_connections",
        response_key="VpnConnections",
        owner_key="",
        id_field="VpnConnectionId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpn-connection/{id}",
        meta_columns=["state", "type", "customer_gateway_id"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Type", ""), x.get("CustomerGatewayId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpn-gateway":                    ResourceConfig(
        describe_method="describe_vpn_gateways",
        response_key="VpnGateways",
        owner_key="",
        id_field="VpnGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpn-gateway/{id}",
        meta_columns=["state", "type"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Type", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "waf-regional":                     ResourceConfig(
        client_name="waf-regional",
        describe_method="list_web_acls",
        response_key="WebACLs",
        owner_key="",
        id_field="WebACLId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:waf-regional:{r}:{a}:webacl/{id}",
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "wafv2":              ResourceConfig(
        client_name="wafv2",
        describe_method="list_web_acls",
        response_key="WebACLs",
        owner_key="",
        id_field="ARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "id"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("Id", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        extra_kwargs={"Scope": "REGIONAL"},
    ),
    "xray-group":                   ResourceConfig(
        client_name="xray",
        describe_method="get_groups",
        response_key="Groups",
        owner_key="",
        id_field="GroupARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["group_name"],
        extract_meta=lambda x: [x.get("GroupName", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "xray-rule":                  ResourceConfig(
        client_name="xray",
        describe_method="get_sampling_rules",
        response_key="SamplingRuleRecords",
        owner_key="",
        id_field="RuleARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["rule_name", "priority", "fixed_rate"],
        extract_meta=lambda x: [x.get("RuleName", ""), str(x.get("Priority", "")), str(x.get("FixedRate", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # get_sampling_rules nests fields under "SamplingRule" -> flatten before use.
        result_filter=lambda records, acc: [rec["SamplingRule"] for rec in records if rec.get("SamplingRule")],
    ),
    # ---- Added from stacklet-resource.json (authored from boto3 API shapes) ----
    "directory": ResourceConfig(
        client_name="ds",
        describe_method="describe_directories",
        response_key="DirectoryDescriptions",
        owner_key="",
        id_field="DirectoryId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ds:{r}:{a}:directory/{id}",
        meta_columns=["name", "edition"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("Edition", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "dlm-policy": ResourceConfig(
        client_name="dlm",
        describe_method="get_lifecycle_policies",
        response_key="Policies",
        owner_key="",
        id_field="PolicyId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:dlm:{r}:{a}:policy/{id}",
        meta_columns=["state", "policy_type"],
        extract_meta=lambda x: [x.get("State", ""), x.get("PolicyType", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "ecs": ResourceConfig(
        client_name="ecs",
        describe_method="list_clusters",
        response_key="clusterArns",
        owner_key="",
        id_field="clusterArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # list_clusters returns bare ARN strings -> wrap each so downstream code can index it.
        result_filter=lambda arns, acc: [{"clusterArn": a} for a in arns],
    ),
    "ecs-task-definition": ResourceConfig(
        client_name="ecs",
        describe_method="list_task_definitions",
        response_key="taskDefinitionArns",
        owner_key="",
        id_field="taskDefinitionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # Returns bare ARN strings (one per revision) -> wrap each into a dict.
        result_filter=lambda arns, acc: [{"taskDefinitionArn": a} for a in arns],
    ),
    "ses-configuration-set": ResourceConfig(
        client_name="ses",
        describe_method="list_configuration_sets",
        response_key="ConfigurationSets",
        owner_key="",
        id_field="Name",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:ses:{r}:{a}:configuration-set/{name}",
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "ses-configuration-set-v2": ResourceConfig(
        client_name="sesv2",
        describe_method="list_configuration_sets",
        response_key="ConfigurationSets",
        owner_key="",
        id_field="Name",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:ses:{r}:{a}:configuration-set/{name}",
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # sesv2 returns bare name strings -> wrap each into a dict.
        result_filter=lambda names, acc: [{"Name": n} for n in names],
    ),
    "workspaces-image": ResourceConfig(
        client_name="workspaces",
        describe_method="describe_workspace_images",
        response_key="Images",
        owner_key="",
        id_field="ImageId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:workspaces:{r}:{a}:workspaceimage/{id}",
        meta_columns=["name", "state", "os"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("State", ""), x.get("OperatingSystem", {}).get("Type", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "workspaces": ResourceConfig(
        client_name="workspaces",
        describe_method="describe_workspaces",
        response_key="Workspaces",
        owner_key="",
        id_field="WorkspaceId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:workspaces:{r}:{a}:workspace/{id}",
        meta_columns=["state", "directory_id", "bundle_id"],
        extract_meta=lambda x: [x.get("State", ""), x.get("DirectoryId", ""), x.get("BundleId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "redshift-snapshot": ResourceConfig(
        client_name="redshift",
        describe_method="describe_cluster_snapshots",
        response_key="Snapshots",
        owner_key="",
        id_field="_arn_id",
        id_column="arn",
        arn_formatter=lambda cid_sid, r, a: f"arn:aws:redshift:{r}:{a}:snapshot:{cid_sid}",
        meta_columns=["cluster_identifier", "status"],
        extract_meta=lambda x: [x.get("ClusterIdentifier", ""), x.get("Status", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        # Redshift snapshot ARN needs BOTH cluster + snapshot id, but arn_formatter
        # only gets id_field. Precompute a "cluster/snapshot" id per record.
        result_filter=lambda snaps, acc: [
            {**s, "_arn_id": f"{s.get('ClusterIdentifier', '')}/{s.get('SnapshotIdentifier', '')}"}
            for s in snaps
        ],
    ),
    "workspaces-directory": ResourceConfig(
        client_name="workspaces",
        describe_method="describe_workspace_directories",
        response_key="Directories",
        owner_key="",
        id_field="DirectoryId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:workspaces:{r}:{a}:directory/{id}",
        meta_columns=["directory_name", "alias", "directory_type"],
        extract_meta=lambda x: [x.get("DirectoryName", ""), x.get("Alias", ""), x.get("DirectoryType", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
}

