"""Resource types are listed below for list-resource-aws.py.
"""

from dataclasses import dataclass
from typing import Any, Callable

@dataclass
class ResourceConfig:
    describe_method: str               # ec2 client method to call
    response_key: str                  # top-level key in the API response
    owner_key: str                     # ownership filter param ("OwnerIds" vs "Owners")
    id_field: str                      # API field name for the resource ID
    id_column: str                     # CSV column name for the ID (forced to "arn")
    meta_columns: list[str]            # non-tag metadata columns before rbrk_* tags
    extract_meta: Callable[[Any], list]
    trailing_columns: list[str]        # columns written after rbrk_* tags (e.g. description)
    extract_trailing: Callable[[Any], list]
    arn_formatter: Callable[[str, str, str], str]  # (id, region, account_id) -> ARN
    result_filter: Callable[[list, str], list] | None = None  # post-fetch filter when API lacks an owner param
    client_name: str = "ec2"          
    is_global: bool = False

RESOURCE_TYPES: dict[str, ResourceConfig] = {
    "snapshot": ResourceConfig(
        describe_method="describe_snapshots",
        response_key="Snapshots",
        owner_key="OwnerIds",
        id_field="SnapshotId",
        id_column="arn",
        meta_columns=["completion_time"],
        extract_meta=lambda s: [s.get("CompletionTime", "")],
        trailing_columns=["description"],
        extract_trailing=lambda s: [s.get("Description", "")],
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}::snapshot/{id}",
    ),
    "ami": ResourceConfig(
        describe_method="describe_images",
        response_key="Images",
        owner_key="Owners",
        id_field="ImageId",
        id_column="arn",
        meta_columns=["creation_date", "state", "architecture"],
        extract_meta=lambda i: [
            i.get("CreationDate", ""),
            i.get("State", ""),
            i.get("Architecture", ""),
        ],
        trailing_columns=["description"],
        extract_trailing=lambda i: [i.get("Description", "")],
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}::image/{id}",
    ),
    "ebs": ResourceConfig(
        describe_method="describe_volumes",
        response_key="Volumes",
        owner_key="",
        id_field="VolumeId",
        id_column="arn",
        meta_columns=["create_time", "size_gb", "state", "volume_type", "availability_zone"],
        extract_meta=lambda v: [
            v.get("CreateTime", ""),
            str(v.get("Size", "")),
            v.get("State", ""),
            v.get("VolumeType", ""),
            v.get("AvailabilityZone", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:volume/{id}",
    ),
    "prefix-list": ResourceConfig(
        describe_method="describe_managed_prefix_lists",
        response_key="PrefixLists",
        owner_key="",
        id_field="PrefixListId",
        id_column="arn",
        meta_columns=["prefix_list_name", "state", "max_entries", "address_family"],
        extract_meta=lambda p: [
            p.get("PrefixListName", ""),
            p.get("State", ""),
            str(p.get("MaxEntries", "")),
            p.get("AddressFamily", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:prefix-list/{id}",
        result_filter=lambda items, _: [i for i in items if i.get("OwnerId") != "aws"],
    ),
    "vpc": ResourceConfig(
        describe_method="describe_vpcs",
        response_key="Vpcs",
        owner_key="",
        id_field="VpcId",
        id_column="arn",  
        arn_formatter=lambda vpc_id, region, account: f"arn:aws:ec2:{region}:{account}:vpc/{vpc_id}",
        meta_columns=["cidr_block", "state", "is_default"],
        extract_meta=lambda v: [
            v.get("CidrBlock", ""),
            v.get("State", ""),
            str(v.get("IsDefault", False)),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "subnet": ResourceConfig(
        client_name="ec2",
        describe_method="describe_subnets",
        response_key="Subnets",
        owner_key="",
        id_field="SubnetId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:subnet/{id}",
        meta_columns=["vpc_id", "cidr_block", "state", "available_ips"],
        extract_meta=lambda s: [
            s.get("VpcId", ""),
            s.get("CidrBlock", ""),
            s.get("State", ""),
            str(s.get("AvailableIpAddressCount", "")),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda items, account: [i for i in items if i.get("OwnerId") == account],
    ),
    "security-group": ResourceConfig(
        client_name="ec2",
        describe_method="describe_security_groups",
        response_key="SecurityGroups",
        owner_key="",
        id_field="GroupId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:security-group/{id}",
        meta_columns=["group_name", "vpc_id"],
        extract_meta=lambda sg: [
            sg.get("GroupName", ""),
            sg.get("VpcId", ""),
        ],
        trailing_columns=["description"],
        extract_trailing=lambda sg: [sg.get("Description", "")],
        result_filter=lambda items, account: [i for i in items if i.get("OwnerId") == account],
    ),
    "network-acl": ResourceConfig(
        client_name="ec2",
        describe_method="describe_network_acls",
        response_key="NetworkAcls",
        owner_key="",
        id_field="NetworkAclId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:network-acl/{id}",
        meta_columns=["vpc_id", "is_default"],
        extract_meta=lambda n: [
            n.get("VpcId", ""),
            str(n.get("IsDefault", False)),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda items, account: [i for i in items if i.get("OwnerId") == account],
    ),
    "internet-gateway": ResourceConfig(
        client_name="ec2",
        describe_method="describe_internet_gateways",
        response_key="InternetGateways",
        owner_key="",
        id_field="InternetGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:internet-gateway/{id}",
        meta_columns=["attachment_state", "vpc_id"],
        extract_meta=lambda ig: [
            ig.get("Attachments", [{}])[0].get("State", "") if ig.get("Attachments") else "detached",
            ig.get("Attachments", [{}])[0].get("VpcId", "") if ig.get("Attachments") else "",
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda items, account: [i for i in items if i.get("OwnerId") == account],
    ),
    "nat-gateway": ResourceConfig(
        client_name="ec2",
        describe_method="describe_nat_gateways",
        response_key="NatGateways",
        owner_key="",
        id_field="NatGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:natgateway/{id}",
        meta_columns=["vpc_id", "subnet_id", "state"],
        extract_meta=lambda n: [
            n.get("VpcId", ""),
            n.get("SubnetId", ""),
            n.get("State", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "log-group": ResourceConfig(
        client_name="logs",
        describe_method="describe_log_groups",
        response_key="logGroups",
        owner_key="",
        id_field="logGroupName",
        id_column="arn",
        arn_formatter=lambda name, r, a: f"arn:aws:logs:{r}:{a}:log-group:{name}",
        meta_columns=["retention_in_days", "creation_time"],
        extract_meta=lambda l: [
            str(l.get("retentionInDays", "Never Expire")),
            str(l.get("creationTime", "")),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "sns": ResourceConfig(
        client_name="sns",
        describe_method="list_topics",
        response_key="Topics",
        owner_key="",
        id_field="TopicArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,  # API returns the full ARN as the ID
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "cfn": ResourceConfig(
        client_name="cloudformation",
        describe_method="describe_stacks",
        response_key="Stacks",
        owner_key="",
        id_field="StackId",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,  # API returns the full ARN as the ID
        meta_columns=["stack_name", "stack_status", "creation_time"],
        extract_meta=lambda s: [
            s.get("StackName", ""),
            s.get("StackStatus", ""),
            str(s.get("CreationTime", "")),
        ],
        trailing_columns=["description"],
        extract_trailing=lambda s: [s.get("Description", "")],
    ),
    "lambda": ResourceConfig(
        client_name="lambda",
        describe_method="list_functions",
        response_key="Functions",
        owner_key="",
        id_field="FunctionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,  # API returns the full ARN as the ID
        meta_columns=["function_name", "runtime", "state"],
        extract_meta=lambda l: [
            l.get("FunctionName", ""),
            l.get("Runtime", ""),
            l.get("State", ""),
        ],
        trailing_columns=["description"],
        extract_trailing=lambda l: [l.get("Description", "")],
    ),
    # RDS 
    "rds": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_instances",
        response_key="DBInstances",
        owner_key="",
        id_field="DBInstanceArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,  # API returns the full ARN
        meta_columns=["engine", "status", "instance_class"],
        extract_meta=lambda db: [
            db.get("Engine", ""),
            db.get("DBInstanceStatus", ""),
            db.get("DBInstanceClass", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_clusters",
        response_key="DBClusters",
        owner_key="",
        id_field="DBClusterArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["engine", "status", "database_name"],
        extract_meta=lambda c: [
            c.get("Engine", ""),
            c.get("Status", ""),
            c.get("DatabaseName", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-snapshot": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_snapshots",
        response_key="DBSnapshots",
        owner_key="",
        id_field="DBSnapshotArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["status", "snapshot_type", "allocated_storage"],
        extract_meta=lambda s: [
            s.get("Status", ""),
            s.get("SnapshotType", ""),
            str(s.get("AllocatedStorage", "")),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster-snapshot": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_cluster_snapshots",
        response_key="DBClusterSnapshots",
        owner_key="",
        id_field="DBClusterSnapshotArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["status", "snapshot_type", "engine"],
        extract_meta=lambda s: [
            s.get("Status", ""),
            s.get("SnapshotType", ""),
            s.get("Engine", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-param-group": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_parameter_groups",
        response_key="DBParameterGroups",
        owner_key="",
        id_field="DBParameterGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["family"],
        extract_meta=lambda p: [p.get("DBParameterGroupFamily", "")],
        trailing_columns=["description"],
        extract_trailing=lambda p: [p.get("Description", "")],
    ),
    "rds-cluster-param-group": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_cluster_parameter_groups",
        response_key="DBClusterParameterGroups",
        owner_key="",
        id_field="DBClusterParameterGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["family"],
        extract_meta=lambda p: [p.get("DBParameterGroupFamily", "")],
        trailing_columns=["description"],
        extract_trailing=lambda p: [p.get("Description", "")],
    ),
    "rds-subnet-group": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_subnet_groups",
        response_key="DBSubnetGroups",
        owner_key="",
        id_field="DBSubnetGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["vpc_id", "subnet_group_status"],
        extract_meta=lambda sg: [
            sg.get("VpcId", ""),
            sg.get("SubnetGroupStatus", ""),
        ],
        trailing_columns=["description"],
        extract_trailing=lambda sg: [sg.get("DBSubnetGroupDescription", "")],
    ),
    "rds-subscription": ResourceConfig(
        client_name="rds",
        describe_method="describe_event_subscriptions",
        response_key="EventSubscriptionsList",
        owner_key="",
        id_field="EventSubscriptionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["status", "sns_topic_arn", "source_type"],
        extract_meta=lambda sub: [
            sub.get("Status", ""),
            sub.get("SnsTopicArn", ""),
            sub.get("SourceType", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    # IAMs
    "iam-role": ResourceConfig(
        client_name="iam",    
        is_global=True,
        describe_method="list_roles",
        response_key="Roles",
        owner_key="",  
        id_field="RoleName", 
        id_column="arn", 
        arn_formatter=lambda region, account, role_name: f"arn:aws:iam::{account}:role/{role_name}",
        meta_columns=["create_date", "max_session_duration"],
        extract_meta=lambda r: [
            str(r.get("CreateDate", "")),
            str(r.get("MaxSessionDuration", "")),
        ],
        trailing_columns=["description"],
        extract_trailing=lambda r: [r.get("Description", "")],
    ),
}