"""Resource types are listed below for list-resource-aws.py.
"""

from dataclasses import dataclass
from typing import Any, Callable

@dataclass
class ResourceConfig:
    describe_method: str               # ec2 client method to call
    response_key: str                  # top-level key in the API response
    owner_key: str                     # ownership filter param ("OwnerIds" vs "Owners")
    id_field: str                      # API field name for the resource ID
    id_column: str                     # CSV column name for the ID (forced to "arn")
    meta_columns: list[str]            # non-tag metadata columns before rbrk_* tags
    extract_meta: Callable[[Any], list]
    trailing_columns: list[str]        # columns written after rbrk_* tags (e.g. description)
    extract_trailing: Callable[[Any], list]
    arn_formatter: Callable[[str, str, str], str]  # (id, region, account_id) -> ARN
    result_filter: Callable[[list, str], list] | None = None  # post-fetch filter when API lacks an owner param
    client_name: str = "ec2"          
    is_global: bool = False
    extra_kwargs: dict | None = None

RESOURCE_TYPES: dict[str, ResourceConfig] = {
    "ec2": ResourceConfig(
        client_name="ec2",
        describe_method="describe_instances",
        response_key="Reservations",
        owner_key="",
        id_field="InstanceId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:instance/{id}",
        meta_columns=["instance_type", "state", "vpc_id"],
        extract_meta=lambda i: [
            i.get("InstanceType", ""),
            i.get("State", {}).get("Name", ""),
            i.get("VpcId", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
        result_filter=lambda res, acc: [i for r in res for i in r.get("Instances", [])],
    ),
    "ami": ResourceConfig(
        describe_method="describe_images",
        response_key="Images",
        owner_key="Owners",
        id_field="ImageId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}::image/{id}",
        meta_columns=["creation_date", "state", "architecture"],
        extract_meta=lambda i: [i.get("CreationDate", ""), i.get("State", ""), i.get("Architecture", "")],
        trailing_columns=["description"],
        extract_trailing=lambda i: [i.get("Description", "")],
    ),
    "ebs": ResourceConfig(
        describe_method="describe_volumes",
        response_key="Volumes",
        owner_key="",
        id_field="VolumeId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:volume/{id}",
        meta_columns=["create_time", "size_gb", "state", "volume_type", "availability_zone"],
        extract_meta=lambda v: [
            v.get("CreateTime", ""), str(v.get("Size", "")), v.get("State", ""),
            v.get("VolumeType", ""), v.get("AvailabilityZone", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "snapshot": ResourceConfig(
        describe_method="describe_snapshots",
        response_key="Snapshots",
        owner_key="OwnerIds",
        id_field="SnapshotId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}::snapshot/{id}",
        meta_columns=["completion_time"],
        extract_meta=lambda s: [s.get("CompletionTime", "")],
        trailing_columns=["description"],
        extract_trailing=lambda s: [s.get("Description", "")],
    ),
    # "ebs-snapshot" is the SAME as "snapshot" (ec2.describe_snapshots).
    # Alias it rather than duplicating; uncomment if your loader needs the key:
    # "ebs-snapshot": <same as "snapshot">,
 
# ---- EC2 networking (were missing) ----------------------------------------
    "vpc": ResourceConfig(
        describe_method="describe_vpcs",
        response_key="Vpcs",
        owner_key="",
        id_field="VpcId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc/{id}",
        meta_columns=["state", "cidr_block", "is_default"],
        extract_meta=lambda x: [x.get("State", ""), x.get("CidrBlock", ""), str(x.get("IsDefault", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "subnet": ResourceConfig(
        describe_method="describe_subnets",
        response_key="Subnets",
        owner_key="",
        id_field="SubnetId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:subnet/{id}",
        meta_columns=["vpc_id", "cidr_block", "availability_zone", "state"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("CidrBlock", ""), x.get("AvailabilityZone", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "security-group": ResourceConfig(
        describe_method="describe_security_groups",
        response_key="SecurityGroups",
        owner_key="",
        id_field="GroupId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:security-group/{id}",
        meta_columns=["group_name", "vpc_id"],
        extract_meta=lambda x: [x.get("GroupName", ""), x.get("VpcId", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "network-acl": ResourceConfig(
        describe_method="describe_network_acls",
        response_key="NetworkAcls",
        owner_key="",
        id_field="NetworkAclId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:network-acl/{id}",
        meta_columns=["vpc_id", "is_default"],
        extract_meta=lambda x: [x.get("VpcId", ""), str(x.get("IsDefault", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "internet-gateway": ResourceConfig(
        describe_method="describe_internet_gateways",
        response_key="InternetGateways",
        owner_key="",
        id_field="InternetGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:internet-gateway/{id}",
        meta_columns=["attached_vpc"],
        extract_meta=lambda x: [(x.get("Attachments") or [{}])[0].get("VpcId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "prefix-list": ResourceConfig(
        describe_method="describe_managed_prefix_lists",
        response_key="PrefixLists",
        owner_key="",
        id_field="PrefixListId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:prefix-list/{id}",
        meta_columns=["prefix_list_name", "state", "address_family"],
        extract_meta=lambda x: [x.get("PrefixListName", ""), x.get("State", ""), x.get("AddressFamily", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "customer-gateway": ResourceConfig(
        describe_method="describe_customer_gateways",
        response_key="CustomerGateways",
        owner_key="",
        id_field="CustomerGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:customer-gateway/{id}",
        meta_columns=["state", "type", "bgp_asn"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Type", ""), str(x.get("BgpAsn", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "flow-log": ResourceConfig(
        describe_method="describe_flow_logs",
        response_key="FlowLogs",
        owner_key="",
        id_field="FlowLogId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc-flow-log/{id}",
        meta_columns=["flow_log_status", "resource_id", "log_destination_type"],
        extract_meta=lambda x: [x.get("FlowLogStatus", ""), x.get("ResourceId", ""), x.get("LogDestinationType", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "key-pair": ResourceConfig(
        describe_method="describe_key_pairs",
        response_key="KeyPairs",
        owner_key="",
        id_field="KeyPairId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:key-pair/{id}",
        meta_columns=["key_name", "key_type", "key_fingerprint"],
        extract_meta=lambda x: [x.get("KeyName", ""), x.get("KeyType", ""), x.get("KeyFingerprint", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "peering-connection": ResourceConfig(
        describe_method="describe_vpc_peering_connections",
        response_key="VpcPeeringConnections",
        owner_key="",
        id_field="VpcPeeringConnectionId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc-peering-connection/{id}",
        meta_columns=["status", "requester_vpc", "accepter_vpc"],
        extract_meta=lambda x: [
            x.get("Status", {}).get("Code", ""),
            x.get("RequesterVpcInfo", {}).get("VpcId", ""),
            x.get("AccepterVpcInfo", {}).get("VpcId", ""),
        ],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "route-table": ResourceConfig(
        describe_method="describe_route_tables",
        response_key="RouteTables",
        owner_key="",
        id_field="RouteTableId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:route-table/{id}",
        meta_columns=["vpc_id"],
        extract_meta=lambda x: [x.get("VpcId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "transit-attachment": ResourceConfig(
        describe_method="describe_transit_gateway_attachments",
        response_key="TransitGatewayAttachments",
        owner_key="",
        id_field="TransitGatewayAttachmentId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:transit-gateway-attachment/{id}",
        meta_columns=["transit_gateway_id", "resource_type", "state"],
        extract_meta=lambda x: [x.get("TransitGatewayId", ""), x.get("ResourceType", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpc-endpoint": ResourceConfig(
        describe_method="describe_vpc_endpoints",
        response_key="VpcEndpoints",
        owner_key="",
        id_field="VpcEndpointId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpc-endpoint/{id}",
        meta_columns=["vpc_id", "service_name", "state"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("ServiceName", ""), x.get("State", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpn-connection": ResourceConfig(
        describe_method="describe_vpn_connections",
        response_key="VpnConnections",
        owner_key="",
        id_field="VpnConnectionId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpn-connection/{id}",
        meta_columns=["state", "type", "customer_gateway_id"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Type", ""), x.get("CustomerGatewayId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "vpn-gateway": ResourceConfig(
        describe_method="describe_vpn_gateways",
        response_key="VpnGateways",
        owner_key="",
        id_field="VpnGatewayId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:vpn-gateway/{id}",
        meta_columns=["state", "type"],
        extract_meta=lambda x: [x.get("State", ""), x.get("Type", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "elastic-ip": ResourceConfig(
        describe_method="describe_addresses",
        response_key="Addresses",
        owner_key="",
        id_field="AllocationId",
        id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:ec2:{r}:{a}:elastic-ip/{id}",
        meta_columns=["public_ip", "domain", "instance_id"],
        extract_meta=lambda x: [x.get("PublicIp", ""), x.get("Domain", ""), x.get("InstanceId", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
 
# ---- RDS (were missing; ARN is in-response -> pass-through, low risk) ------
    "rds": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_instances",
        response_key="DBInstances",
        owner_key="",
        id_field="DBInstanceArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["db_instance_class", "engine", "status"],
        extract_meta=lambda x: [x.get("DBInstanceClass", ""), x.get("Engine", ""), x.get("DBInstanceStatus", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_clusters",
        response_key="DBClusters",
        owner_key="",
        id_field="DBClusterArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["engine", "status", "engine_mode"],
        extract_meta=lambda x: [x.get("Engine", ""), x.get("Status", ""), x.get("EngineMode", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-snapshot": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_snapshots",
        response_key="DBSnapshots",
        owner_key="",
        id_field="DBSnapshotArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["snapshot_type", "status", "engine"],
        extract_meta=lambda x: [x.get("SnapshotType", ""), x.get("Status", ""), x.get("Engine", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster-snapshot": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_cluster_snapshots",
        response_key="DBClusterSnapshots",
        owner_key="",
        id_field="DBClusterSnapshotArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["snapshot_type", "status", "engine"],
        extract_meta=lambda x: [x.get("SnapshotType", ""), x.get("Status", ""), x.get("Engine", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-param-group": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_parameter_groups",
        response_key="DBParameterGroups",
        owner_key="",
        id_field="DBParameterGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["db_parameter_group_family"],
        extract_meta=lambda x: [x.get("DBParameterGroupFamily", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-cluster-param-group": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_cluster_parameter_groups",
        response_key="DBClusterParameterGroups",
        owner_key="",
        id_field="DBClusterParameterGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["db_parameter_group_family"],
        extract_meta=lambda x: [x.get("DBParameterGroupFamily", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-subnet-group": ResourceConfig(
        client_name="rds",
        describe_method="describe_db_subnet_groups",
        response_key="DBSubnetGroups",
        owner_key="",
        id_field="DBSubnetGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["vpc_id", "status"],
        extract_meta=lambda x: [x.get("VpcId", ""), x.get("SubnetGroupStatus", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "rds-subscription": ResourceConfig(
        client_name="rds",
        describe_method="describe_event_subscriptions",
        response_key="EventSubscriptionsList",
        owner_key="",
        id_field="EventSubscriptionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["source_type", "status", "sns_topic_arn"],
        extract_meta=lambda x: [x.get("SourceType", ""), x.get("Status", ""), x.get("SnsTopicArn", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
 
# ---- CloudFormation (was missing; StackId IS the ARN) ---------------------
    "cfn": ResourceConfig(
        client_name="cloudformation",
        describe_method="describe_stacks",
        response_key="Stacks",
        owner_key="",
        id_field="StackId",              # StackId is already a full ARN
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["stack_name", "stack_status", "creation_time"],
        extract_meta=lambda x: [x.get("StackName", ""), x.get("StackStatus", ""), str(x.get("CreationTime", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
 
# ---- Other services (ARN in response -> pass-through) ---------------------
    "lambda": ResourceConfig(
        client_name="lambda",
        describe_method="list_functions",
        response_key="Functions",
        owner_key="",
        id_field="FunctionArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["function_name", "runtime", "state"],
        extract_meta=lambda l: [l.get("FunctionName", ""), l.get("Runtime", ""), l.get("State", "")],
        trailing_columns=["description"],
        extract_trailing=lambda l: [l.get("Description", "")],
    ),
    "sns": ResourceConfig(
        client_name="sns",
        describe_method="list_topics",
        response_key="Topics",
        owner_key="",
        id_field="TopicArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=[],
        extract_meta=lambda _: [],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "acm-certificate": ResourceConfig(
        client_name="acm",
        describe_method="list_certificates",
        response_key="CertificateSummaryList",
        owner_key="",
        id_field="CertificateArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["domain_name", "status"],
        extract_meta=lambda x: [x.get("DomainName", ""), x.get("Status", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "app-elb": ResourceConfig(
        client_name="elbv2",
        describe_method="describe_load_balancers",
        response_key="LoadBalancers",
        owner_key="",
        id_field="LoadBalancerArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["dns_name", "type", "state"],
        extract_meta=lambda x: [x.get("DNSName", ""), x.get("Type", ""), x.get("State", {}).get("Code", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "app-elb-target-group": ResourceConfig(
        client_name="elbv2",
        describe_method="describe_target_groups",
        response_key="TargetGroups",
        owner_key="",
        id_field="TargetGroupArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["target_group_name", "protocol", "port"],
        extract_meta=lambda x: [x.get("TargetGroupName", ""), x.get("Protocol", ""), str(x.get("Port", ""))],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "secrets-manager": ResourceConfig(
        client_name="secretsmanager",
        describe_method="list_secrets",
        response_key="SecretList",
        owner_key="",
        id_field="ARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "last_changed_date"],
        extract_meta=lambda x: [x.get("Name", ""), str(x.get("LastChangedDate", ""))],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "event-bus": ResourceConfig(
        client_name="events",
        describe_method="list_event_buses",
        response_key="EventBuses",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "event-rule": ResourceConfig(
        client_name="events",
        describe_method="list_rules",
        response_key="Rules",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "state"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("State", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    "ecr": ResourceConfig(
        client_name="ecr",
        describe_method="describe_repositories",
        response_key="Repositories",
        owner_key="",
        id_field="repositoryArn",         # NOTE: ecr uses lowercase field names
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["repository_name", "repository_uri"],
        extract_meta=lambda x: [x.get("repositoryName", ""), x.get("repositoryUri", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "xray-group": ResourceConfig(
        client_name="xray",
        describe_method="get_groups",
        response_key="Groups",
        owner_key="",
        id_field="GroupARN",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["group_name"],
        extract_meta=lambda x: [x.get("GroupName", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "appstream-fleet": ResourceConfig(
        client_name="appstream",
        describe_method="describe_fleets",
        response_key="Fleets",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name", "state", "instance_type"],
        extract_meta=lambda x: [x.get("Name", ""), x.get("State", ""), x.get("InstanceType", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
    "appstream-stack": ResourceConfig(
        client_name="appstream",
        describe_method="describe_stacks",
        response_key="Stacks",
        owner_key="",
        id_field="Arn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["name"],
        extract_meta=lambda x: [x.get("Name", "")],
        trailing_columns=["description"],
        extract_trailing=lambda x: [x.get("Description", "")],
    ),
    # describe_alarms ALSO returns "CompositeAlarms" separately — metric only here.
    "alarm": ResourceConfig(
        client_name="cloudwatch",
        describe_method="describe_alarms",
        response_key="MetricAlarms",
        owner_key="",
        id_field="AlarmArn",
        id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["alarm_name", "state_value", "metric_name"],
        extract_meta=lambda x: [x.get("AlarmName", ""), x.get("StateValue", ""), x.get("MetricName", "")],
        trailing_columns=[],
        extract_trailing=lambda _: [],
    ),
 
# ---- Global resources (need is_global=True + engine support) --------------
    "iam-role": ResourceConfig(
        client_name="iam", describe_method="list_roles", response_key="Roles",
        owner_key="", id_field="Arn", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["role_name", "create_date", "path"],
        extract_meta=lambda x: [x.get("RoleName", ""), str(x.get("CreateDate", "")), x.get("Path", "")],
        trailing_columns=["description"], extract_trailing=lambda x: [x.get("Description", "")],
        is_global=True,
        # TAG WARNING: RGT GetResources does NOT support IAM roles -> empty tags.
        # Needs native iam.list_role_tags(RoleName=...).
    ),
    "iam-user": ResourceConfig(
        client_name="iam", describe_method="list_users", response_key="Users",
        owner_key="", id_field="Arn", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["user_name", "create_date", "path"],
        extract_meta=lambda x: [x.get("UserName", ""), str(x.get("CreateDate", "")), x.get("Path", "")],
        trailing_columns=[], extract_trailing=lambda _: [],
        is_global=True,
        # TAG WARNING: RGT GetResources does NOT support IAM users -> empty tags.
        # Needs native iam.list_user_tags(UserName=...).
    ),
    "iam-policy": ResourceConfig(
        client_name="iam", describe_method="list_policies", response_key="Policies",
        owner_key="", id_field="Arn", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["policy_name", "attachment_count", "create_date"],
        extract_meta=lambda x: [x.get("PolicyName", ""), str(x.get("AttachmentCount", "")), str(x.get("CreateDate", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        extra_kwargs={"Scope": "Local"},   # needs the extra_kwargs engine tweak
        is_global=True,
    ),
    "distribution": ResourceConfig(
        client_name="cloudfront", describe_method="list_distributions",
        response_key="DistributionList", owner_key="",
        id_field="ARN", id_column="arn",
        arn_formatter=lambda arn, r, a: arn,
        meta_columns=["domain_name", "status", "enabled"],
        extract_meta=lambda x: [x.get("DomainName", ""), x.get("Status", ""), str(x.get("Enabled", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        result_filter=lambda res, acc: res.get("Items", []) if isinstance(res, dict) else [],
        is_global=True,
    ),
    "hostedzone": ResourceConfig(
        client_name="route53", describe_method="list_hosted_zones",
        response_key="HostedZones", owner_key="",
        id_field="Id", id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:route53:::hostedzone/{id.split('/')[-1]}",
        meta_columns=["zone_name", "record_count", "private"],
        extract_meta=lambda x: [x.get("Name", ""), str(x.get("ResourceRecordSetCount", "")), str(x.get("Config", {}).get("PrivateZone", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        is_global=True,
    ),
    "s3": ResourceConfig(
        client_name="s3", describe_method="list_buckets", response_key="Buckets",
        owner_key="", id_field="Name", id_column="arn",
        arn_formatter=lambda id, r, a: f"arn:aws:s3:::{id}",
        meta_columns=["creation_date"],
        extract_meta=lambda x: [str(x.get("CreationDate", ""))],
        trailing_columns=[], extract_trailing=lambda _: [],
        is_global=True,
        # TAG WARNING: RGT returns S3 tags only from the bucket's HOME region.
        # is_global pins the tag client to us-east-1 -> non-us-east-1 buckets get
        # empty tags. Use native s3.get_bucket_tagging(Bucket=...) if you need them.
    ),
}